version: '3.9'

services:
  app:
    build: .
    ports:
      - "${PORT}:8000"
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    expose: 
      - 5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}